import type { Metadata } from "next";
import {
  inter,
  roboto,
  poppins,
  montserrat,
  lato,
  oswald,
  source,
  openSans,
} from "@/components/ui/fonts";
import "./globals.css";

export const metadata: Metadata = {
  title: "hola netxjs ",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      data-theme="dark"
      className={`
      ${inter.variable}
      ${roboto.variable}
      ${poppins.variable}
      ${montserrat.variable}
      ${lato.variable}
      ${oswald.variable}
      ${source.variable}
      ${openSans.variable}
    `}
    >
      <body className="font-inter antialiased">{children}</body>
    </html>
  );
}
